### ISSUE TITLE
Chrome宽屏插件

### ISSUE THREAD

**Issue by iamleeron** [adamlui/chatgpt-apps#1]
Hello，首先感谢这个一直在寻找的工具。有个问题咨询下：

**是否2023.5.31.3版本，在Chrome重新打开后从全屏（显示tab）模式退出，再全屏会进入隐藏tab的全屏？**

我chagtpt一直作为pined tab常驻chrome的。非常感谢！！

**Comment by adamlui** [comment]
@iamleeron 嘿，我的中文很糟糕，所以我正在使用谷歌翻译，你是在问如果你打开了多个标签，它应该记住你的屏幕状态吗？ 如果是这样，答案是肯定的！ 尝试打开多个 chatgpt 选项卡，然后在其中一个中单击全屏。 换一个，它也会进入全屏！

**Comment by iamleeron** [comment]
Thanks! My question is: 

**Would version 2023.5.31.3 of "ChatGPT Widescreen mode" cause the Chrome tab bar to be hidden when entering full-screen mode upon restart of Chrome?** 

My usage habit is to always keep ChatGPT pinned as a tab in Chrome, but recently whenever I open Chrome, it exit full-screen mode, and upon re-entering full-screen, the tab bar will be hidden.

Thanks a lot!

**Comment by adamlui** [comment]
@iamleeron sorry I don't understand. Are you referring to Chrome's F11 Fullscreen, or ChatGPT Fullscreen (which doesn't enter Fullscreen but expands content to the window edges)?

**Comment by iamleeron** [comment]
These are the two different full-screen modes in macOS, and I'm not entirely sure if they're related to your extension.
<img width="1390" alt="Screenshot 2023-06-01 at 19 33 49" src="https://github.com/adamlui/chatgpt-apps/assets/129355548/69cfd07c-19fb-4cbd-a3c0-1bc390391725">

**Comment by adamlui** [comment]
@iamleeron I see, the right fullscreen happens when you press `Ctrl`+`⌘`+`F` or `F11` or click `View` → `Enter Full Screen` in Chrome, it is not caused by my extension (although I am thinking of adding an option to enter full-screen mode w/ no tabs, too)

So when you restart Chrome, its behavior is to never make tab bar disappear. But would you like an option to make bar disappear when you restart Chrome?

**Comment by iamleeron** [comment]
It depends on, but I prefer to give users options and not make changes to their settings without their permission.
 
I have an idea. If you could provide an additional "floating window" feature that allows a ChatGPT to be displayed on top of any window, that would be awesome! It could become a system-level application. You can refer to this Youtube floating window extension https://chrome.google.com/webstore/detail/floating-player-picture-i/nalkmonnmldhpfcpdlbdpljlaajlaphh.

**Comment by adamlui** [comment]
That is a great idea! In the meantime, what do you think of an option to also enter no-bar fullscreen mode if clicking full-window? So if this option is enabled, restarting Chrome when you were in full-window will make bar disappear?

**Comment by iamleeron** [comment]
In my opinion, Chrome does have that feature, although it may not be in high demand by many people.

**Comment by adamlui** [comment]
@iamleeron chrome has the feature to restart with no tabs bar?

**Comment by adamlui** [comment]
@iamleeron so your problem was, you thought fullscreen mode by ChatGPT Widescreen caused bar to disappear, but now you know that is not the case, there is no issue? Also how are you entering fullscreen causing bar to disappear, what do you click?

**Comment by adamlui** [comment]
@iamleeron the latest version has a fullscreen toggle now:
![image](https://github.com/adamlui/chatgpt-apps/assets/10906554/a9a252c4-13f5-4078-bb9b-164f3bec8ab9)

**Comment by iamleeron** [comment]
Thanks for letting me know, I will take a look later.
