### ISSUE TITLE
GPT网页版改版后，原本全屏的图标出现了显示错误

### ISSUE THREAD

**Issue by justsonghua** [adamlui/chatgpt-apps#14]
![Snipaste_2023-11-07_15-45-02](https://github.com/adamlui/chatgpt-apps/assets/41994375/27115a6a-5f90-41b0-bf10-e9a7a84ebe0c)

如图所示，11月7日，GPT网页版改版后，全屏等图标出现了显示错误。

**Comment by adamlui** [comment]
@justsonghua 感谢您报告此事。 您的浏览器和用户脚本管理器是什么？

**Comment by justsonghua** [comment]
Chrome浏览器：Version 119.0.6045.106 (Official Build) (64-bit)

用户脚本管理器我不太清楚，我是直接在Chrome插件商店安装的。

**Comment by adamlui** [comment]
@justsonghua 哦，您的意思是您安装了 ChatGPT 宽屏 Chrome 扩展程序？ 如果是这样，您可以转到 chrome://extensions/ 吗？ChatGPT 宽屏模式旁边的版本说明了什么？ 另外你的操作系统是什么？

**Comment by adamlui** [comment]
@justsonghua 事实上，我的界面仍然是旧的（其中发送按钮不像你的那样是方形的，头像也不像你的那样是圆形的）所以我无法修复它，直到他们决定更新我的界面:(

**Comment by justsonghua** [comment]
版本
2023年10月30日
更新
2023 年 11 月 1 日

操作系统是Win11 23H2

**Comment by justsonghua** [comment]
> @justsonghua 事实上，我的界面仍然是旧的（其中发送按钮不像你的那样是方形的，头像也不像你的那样是圆形的）所以我无法修复它，直到他们决定更新我的界面 :(

好吧，也有可能是GPT给我推了一些测试中的UI。我需要关闭这个问题吗？还是

**Comment by adamlui** [comment]
@justsonghua 如果您相信我，也许我可以用您的帐户登录来体验新界面？ 这样我就可以更快地修复，否则我们必须等待我的界面更新

**Comment by justsonghua** [comment]
> @justsonghua 如果您相信我，也许我可以用您的帐户登录来体验新界面？ 这样我就可以更快地修复，否则我们必须等待我的界面更新

这个可能不太方便，我这周也要一直使用GPT，可能我的不定时登录会影响到你的修复。如果这周你都没有收到新界面推送的话。下周我不介意你使用我的界面来修复这个问题。实在不好意思，这周太忙了。

**Comment by adamlui** [comment]
好吧，让我们等待并希望

**Comment by adamlui** [comment]
@justsonghua 嘿，现在对你有用吗？

**Comment by justsonghua** [comment]
> @justsonghua 嘿，现在对你有用吗？

时好时坏吧，感觉GPT每次后台更新后都会有点小问题，但不知道什么时候又能用了。
