### ISSUE TITLE
why it takes so long to use Widescreen ?

### ISSUE THREAD

**Issue by SwissFred57** [adamlui/chatgpt-apps#20]
when i start Chatgpt 4 it take about 14 seconds to use widescreen why ?
also sometimes the response window get cleared

**Comment by adamlui** [comment]
You mean the buttons take 14 seconds to appear? Also what is the repsonse window and what is cleared

**Comment by adamlui** [comment]
If you turn off chat history, the screen clears every 10 minutes (OpenAI decision not mine) but my script ChatGPT Auto Refresh prevents this
