### ISSUE TITLE
Widescreen not working

### ISSUE THREAD

**Issue by NoooneyDude** [adamlui/chatgpt-apps#22]
Widescreen not working. All options are checked including the main toggle switch top-right.

Every time I switch tabs the main toggle switch reverts to disabled state.

- Google Chrome Version 120.0.6099.129 (Official Build) (64-bit)
- Windows 10

![xtr4Lr0 1](https://github.com/adamlui/chatgpt-apps/assets/6926225/58771b25-f367-4d91-91fa-d3b82d159a60)

![](https://i.imgur.com/OK2o5fS.png)

May be of interest to you:
![](https://i.imgur.com/ZlqBhSc.png)

**Comment by adamlui** [comment]
Hey @NoooneyDude thanks for reporting this! I made some changes tested to work that will probably publish on the store tomorrow, but when it shows version is 2023.12.23, can you remove your old version this time before installing it?

**Comment by adamlui** [comment]
Hey it got updated today @NoooneyDude can you check it out?

**Comment by NoooneyDude** [comment]
Looks good @adamlui ! Thank you!
