### ISSUE TITLE
Edge浏览器下宽屏模式插件报错

### ISSUE THREAD

**Issue by hopana** [adamlui/chatgpt-apps#25]
现象：Edge浏览器下无法实现宽屏模式，console报错：TypeError: Cannot read properties of undefined (reading 'toString')

原因：ChatGPT语言设置为了“简体中文”，因此，插件chatgpt.js 288行报错：`document.querySelectorAll('nav[aria-label="Chat history"] div')`

解决：`document.querySelectorAll('nav[aria-label="Chat history"] || document.querySelectorAll('nav[aria-label="聊天记录"]`

**Comment by hopana** [comment]
> 现象：Edge浏览器下无法实现宽屏模式，console报错：TypeError: Cannot read properties of undefined (reading 'toString')
> 
> 原因：ChatGPT语言设置为了“简体中文”，因此，插件chatgpt.js 288行报错：`document.querySelectorAll('nav[aria-label="Chat history"] div')`
> 
> 解决：`document.querySelectorAll('nav[aria-label="Chat history"] || document.querySelectorAll('nav[aria-label="聊天记录"]`

当然最好的解决方式是根据用户设置的语言，动态来查询div

**Comment by adamlui** [comment]
嘿 @hopana 抱歉这么晚回复，我没有注意到这个问题，但是由于您的观察，我已将其修复为依赖 SVG 子元素属性而不是标签。 你能告诉我现在是否有效吗？ 用户脚本现已上线，但 Edge 版本需要几天时间才能批准并出现在商店中
