### ISSUE TITLE
change hu message string

### ISSUE THREAD

**Issue by sanchomuzax** [adamlui/chatgpt-apps#30]
https://github.com/adamlui/chatgpt-apps/blob/f20bb0204976f13e2180f86505cd931819bb22f7/chatgpt-auto-refresh/greasemonkey/_locales/hu/messages.json#L4

![image](https://github.com/adamlui/chatgpt-apps/assets/2911588/b41a37c4-86c1-4af6-ade7-322fc94f7314)

Please, update it:
` "menuLabel_autoRefresh": { "message": "Automatikus frissítés" },`

to:

` "menuLabel_autoRefresh": { "message": "Auto frissítés" },`

**Comment by adamlui** [comment]
I updated it thanks @sanchomuzax!
