### ISSUE TITLE
Input text is outside of text area 

### ISSUE THREAD

**Issue by mrbacky** [adamlui/chatgpt-apps#83]
Hello,

I noticed today an issue with text area. See the screenshots below.

<img width="1496" alt="Screenshot 2024-09-12 at 22 59 08" src="https://github.com/user-attachments/assets/b5916483-6027-4d2c-98f9-047479209136">

---

<img width="1496" alt="Screenshot 2024-09-12 at 23 06 36" src="https://github.com/user-attachments/assets/fa18ba05-5cbf-4603-95aa-c7cd0c980b85">

**Comment by adamlui** [comment]
Hey @mrbacky thanks for reporting, what version of the userscript or extension are you using, and browser? I did notice this before but had fixed it in a prev update but am curious if it is still occurring

**Comment by mrbacky** [comment]
Im using 2024.9.12 version of the ChatGPT Widescreen Mode extension and im using chrome browser.

I am also having this issue. 
<img width="1025" alt="Screenshot 2024-09-14 at 00 51 27" src="https://github.com/user-attachments/assets/6fec08f1-0ebd-452d-93ef-74e95b3e4bb2">



Im using Wide GPT extension instead then.

**Comment by adamlui** [comment]
I fixed the second issue it should go away on auto-update, the 1st one if it occurs for me I can fix, if for you it would be belpful if you can inspect element so I know the CSS styles being applied to the chat box

**Comment by adamlui** [comment]
Also may I know the reason you prefer this over Wide GPT without such issues?

**Comment by mrbacky** [comment]
Not sure if these screenshots will help u somehow. 
some elements are on top of other elements.

No issues with text area anymore 👍

<img width="1512" alt="Screenshot 2024-09-14 at 14 10 34" src="https://github.com/user-attachments/assets/be08d79b-ee05-4241-9647-b11367988092">
<img width="1512" alt="Screenshot 2024-09-14 at 14 10 10" src="https://github.com/user-attachments/assets/f4a1821f-84a1-4775-ae64-ad800317407b">


I meant that I am using Wide GPT since the ChatGPT Widescreen Mode is a bit buggy.

**Comment by adamlui** [comment]
@mrbacky I fixed both issues already, your feedbacck was 1 published update behind, the overlapping text is fixed in 2024.9.13 but it is weekend for Google so will be approved tomorrow

**Comment by adamlui** [comment]
> I meant that I am using Wide GPT now

But why did you use ChatGPT Widescreen instead of Wide GPT without the new bugs

**Comment by mrbacky** [comment]
> > I meant that I am using Wide GPT now
> 
> But why did you use ChatGPT Widescreen instead of Wide GPT without the new bugs

I found ChatGPT Widescreen first, and then i found Wide GPT. It solves same problem so I don't care which one I use actually.

**Comment by adamlui** [comment]
Is there a feature you want I can add to get you to switch back after the 2024.9.13 update publishes tomorrow
